title: "Workshop basics: Lasercut enclosures"
hero_image: images/banner.jpg
description: Making the case for cases
theme: blue # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: 
interests: 
technologies: 
site_areas: HackSpace
steps:
  - title: Introduction
  - title: The options
  - title: Finger joints
  - title: Mortise & Tenon Joints
  - title: Captive nut
