---
title: 'Workshop basics: laser-cut enclosures'
hero_image: images/banner.jpg
description: Making the case for cases
theme: blue
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 
interests: 
technologies: 
site_areas: HackSpace
steps:
- title: Introduction
- title: The options
- title: Finger joints
- title: Mortise and tenon joints
- title: Captive nut and screw T-slot joints
