---
title: 'Workshop basics: laser-cut enclosures'
hero_image: images/banner.jpg
description: Making the case for cases
theme: blue
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum:
interests:
technologies:
site_areas: HackSpace
steps:
- title: Introduction
  completion: engaged
- title: The options
- title: Finger joints
- title: Mortise and tenon joints
  completion: internal
- title: Captive nut and screw T-slot joints
